# OpenRemote v3
#
# Profile for building the services using docker compose.
#
# Please see deploy.yml for configuration details for each service.
#
version: '2.4'

services:

  proxy:
    image: openremote/proxy:${DATE_TAG:-latest}
    build: '../proxy'

  manager:
    image: openremote/manager:${DATE_TAG:-latest}
    build: '../manager/build/install/manager'

  keycloak:
    image: openremote/keycloak:${DATE_TAG:-latest}
    build: '../keycloak'

  postgresql:
    image: openremote/postgresql:${DATE_TAG:-latest}
    build: '../postgresql'

  map:
    image: openremote/map:${DATE_TAG:-latest}
    build: '../map'

  swarm:
    image: openremote/manager-swarm:${DATE_TAG:-latest}
    build:
      context: '../manager/build/install/manager'
      dockerfile: swarm.Dockerfile
